=== Jasig/CampusLifePortlets/src/main/resources/xsd/computerlabs.xsd
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<xs:schema xmlns="https://source.jasig.org/schemas/portlet/computerlabs"
    targetNamespace="https://source.jasig.org/schemas/portlet/computerlabs"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:element name="computer-lab-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="computer-lab" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="computer-lab">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="computer-type" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="location-code" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="computer-type">
        <xs:complexType>
            <xs:attribute name="key" type="xs:string"/>
            <xs:attribute name="message-key" type="xs:string"/>
            <xs:attribute name="icon-key" type="xs:string"/>
            <xs:attribute name="available" type="xs:string"/>
            <xs:attribute name="total" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== Jasig/CampusLifePortlets/src/main/resources/mock-data/computer-labs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<computer-lab-list xmlns="https://source.jasig.org/schemas/portlet/computerlabs"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/portlet/computerlabs ../xsd/computerlabs.xsd">

    <computer-lab name="Bass Library" location-code="BASSLB">
        <computer-type key="PC" message-key="computer.type.pc"
            icon-key="pc" available="5" total="12" />
        <computer-type key="Mac" message-key="computer.type.mac"
            icon-key="mac" available="5" total="12" />
    </computer-lab>

    <computer-lab name="Dunham" location-code="DL">
        <computer-type key="PC" message-key="computer.type.pc"
            icon-key="pc" available="2" total="10" />
        <computer-type key="Mac" message-key="computer.type.mac"
            icon-key="mac" available="10" total="15" />
    </computer-lab>

    <computer-lab name="CTHall" location-code="C">
        <computer-type key="PC" message-key="computer.type.pc"
            icon-key="pc" available="10" total="12" />
        <computer-type key="Mac" message-key="computer.type.mac"
            icon-key="mac" available="3" total="8" />
    </computer-lab>

</computer-lab-list>
