=== Jasig/CampusLifePortlets/src/main/resources/xsd/menu.xsd
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<xs:schema xmlns="https://source.jasig.org/schemas/portlet/dining/menu"
    targetNamespace="https://source.jasig.org/schemas/portlet/dining/menu"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dining-hall" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="day" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="dining-hall">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="meal" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="meal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="food-category" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="food-category">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dish" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="dish">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="code" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="nutrition-item" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="ingredients" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="nutrition-item">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Jasig/CampusLifePortlets/src/main/resources/mock-data/berkeley.xml
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<menu
    xmlns="https://source.jasig.org/schemas/portlet/dining/menu"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/portlet/dining/menu ../xsd/menu.xsd"
    day="Today">
    
    <dining-hall name="Berkeley">
        <meal name="Continental Breakfast">
            <food-category name="The Entrees">
                <dish name="Waffle Bar">
                    <code>G</code>
                </dish>
            </food-category>
            <food-category name="Morning Sweets">
                <dish name="Ham and Cheese Scones">
                    <code>D</code>
                    <code>E</code>
                    <code>P</code>
                    <code>G</code>
                </dish>
            </food-category>
        </meal>
        <meal name="Lunch">
            <food-category name="Soup">
                <dish name="Yankee Bean Soup">
                    <code>SY</code>
                </dish>
            </food-category>
            <food-category name="Entrees">
                <dish name="Citrus and Cilantro Tofu">
                    <code>SM</code>
                    <code>V</code>
                    <code>SY</code>
                    <code>G</code>
                </dish>
                <dish name="Conrmeal-Crusted Catfish">
                    <code>SY</code>
                    <code>G</code>
                </dish>
                <dish name="Mediterranean Foccacia">
                    <code>D</code>
                    <code>W</code>
                    <code>G</code>
                </dish>
                <dish name="BBQ Chicken Breast Sandwich">
                    <code>W</code>
                    <code>G</code>
                </dish>
            </food-category>
            <food-category name="Grill">
                <dish name="Grilled-to-order Star Ranch All Natural Burgers and Cheeseburgers, All Natural Chicken Breasts, Jumbo All Beef Franks, Gardenburgers The Original, Gardenburger Black Bean Veggie Burgers, or Grilled Tofu, plus French Fries."></dish>
            </food-category>
            <food-category name="Market Deli">
                <dish name="Italian Deli Zep">
                    <code>D</code>
                    <code>P</code>
                    <code>W</code>
                    <code>G</code>
                </dish>
            </food-category>
            <food-category name="Sides">
                <dish name="Rice"></dish>
            </food-category>
            <food-category name="Vegetables">
                <dish name="Southern Style Collard Greens">
                    <code>A</code>
                </dish>
            </food-category>
            <food-category name="Salad">
                <dish name="Mesclun, Cauliflower and Cheddar">
                    <code>A</code>
                </dish>
                <dish name="White Bean Salad with Sundried Tomato Vinaigrette">
                    <code>A</code>
                </dish>
                <dish name="Combination Salad">
                    <code>A</code>
                    <code>SY</code>
                </dish>
            </food-category>
        </meal>
        <meal name="Dinner">
            <food-category name="Entrees">
                <dish name="Apricot Roasted Chicken">
                    <code>A</code>
                    <code>D</code>
                </dish>
                <dish name="Roast Chicken Picnic Pieces"></dish>
            </food-category>
            <food-category name="Chef's Table">
                <dish name="Sage Aioli">
                    <code>E</code>
                </dish>
                <dish name="Sweet and Smokey Roast Pork">
                    <code>A</code>
                    <code>P</code>
                </dish>
            </food-category>
            <food-category name="Grill">
                <dish name="SautÃ©ed Swiss Chard with Beans and Bread">
                    <code>W</code>
                    <code>G</code>
                </dish>
                <dish name="Grilled-to-order Star Ranch All Natural Burgers and Cheeseburgers, All Natural Chicken Breasts, Jumbo All Beef Franks, Gardenburgers The Original, Gardenburger Black Bean Veggie Burgers, or Grilled Tofu, plus French Fries."></dish>
            </food-category>
            <food-category name="Sides">
                <dish name="Israeli Couscous"></dish>
            </food-category>
            <food-category name="Vegetables">
                <dish name="Broccoli With Lemon, Olive Oil and Garlic"></dish>
            </food-category>
            <food-category name="Salad">
                <dish name="Mesclun, Cauliflower and Cheddar">
                    <code>A</code>
                </dish>
                <dish name="White Bean Salad with Sundried Tomato Vinaigrette">
                    <code>A</code>
                </dish>
                <dish name="Combination Salad">
                    <code>A</code>
                    <code>SY</code>
                </dish>
            </food-category>
        </meal>
    </dining-hall>
    
</menu>

=== Jasig/CampusLifePortlets/src/main/webapp/data/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed to Jasig under one or more contributor license agreements. See the 
    NOTICE file distributed with this work for additional information regarding copyright 
    ownership. Jasig licenses this file to you under the Apache License, Version 2.0 
    (the "License"); you may not use this file except in compliance with the License. 
    You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0 
    Unless required by applicable law or agreed to in writing, software distributed under 
    the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS 
    OF ANY KIND, either express or implied. See the License for the specific language 
    governing permissions and limitations under the License. -->
<menu xmlns="https://source.jasig.org/schemas/portlet/dining/menu"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/portlet/dining/menu ../xsd/menu.xsd">

    <menu-day date="2012-06-11">
        <dining-hall key="1" name="General">
            <meal name="Breakfast">
                <food-category name="First Course">
                    <dish name="Steelcut Oats "/>
                </food-category>
                <food-category name="The Entrees">
                    <dish name="Waffle Bar "/>
                </food-category>
                <food-category name="Morning Sweets">
                    <dish name="Cheddar &amp;amp; Green Onion Scone "/>
                </food-category>
            </meal>
            <meal name="Lunch">
                <food-category name="The Soup">
                    <dish name="Vegetarian French Onion Soup "/>
                    <dish name="Manhattan Clam Chowder "/>
                </food-category>
                <food-category name="The Entrees">
                    <dish name="Marinated Oven Roasted Tofu "/>
                    <dish name="Spinach Frittata With Ricotta "/>
                </food-category>
                <food-category name="The Express Bar">
                    <dish name="Cheese Sauce"/>
                    <dish name="Steakhouse French Fries "/>
                    <dish name="Brown Sauce"/>
                    <dish name="Black Pepper Mayonnaise "/>
                </food-category>
                <food-category name="The Grill">
                    <dish name="Hand Shaped Angus Hamurger "/>
                    <dish name="Hand Shaped Angus Cheeseburger "/>
                    <dish
                        name="Grilled-to-order Star Ranch All Natural Burgers &amp;amp; Cheeseburgers, All Natural Chicken Breasts, Jumbo All Beef Franks, Gardenburgers The Original, Gardenburger Black Bean Veggie Burgers, or Grilled Tofu, plus French Fries."/>
                </food-category>
                <food-category name="The Deli">
                    <dish name="Egg Salad Mixture "/>
                </food-category>
                <food-category name="The Vegetables">
                    <dish name="Baked Zucchini &amp;amp; Tomatoes "/>
                </food-category>
                <food-category name="The Salad">
                    <dish name="Mesclun, Fresh Mozzarella &amp;amp; Olives "/>
                    <dish name="Broccoli Olive &amp;amp; Ricotta Salata Salad "/>
                    <dish name="German Potato Salad "/>
                </food-category>
                <food-category name="The Sweets">
                    <dish name="Rootbeer Cupcake "/>
                    <dish name="Chocolate Chip Cookie "/>
                </food-category>
            </meal>
        </dining-hall>
    </menu-day>

    <menu-day date="2012-06-12">
        <dining-hall key="1" name="General">
            <meal name="Breakfast">
                <food-category name="First Course">
                    <dish name="Steelcut Oats "/>
                </food-category>
                <food-category name="The Entrees">
                    <dish name="Waffle Bar "/>
                </food-category>
                <food-category name="Morning Sweets">
                    <dish name="Cheddar &amp;amp; Green Onion Scone "/>
                </food-category>
            </meal>
            <meal name="Lunch">
                <food-category name="The Soup">
                    <dish name="Vegetarian French Onion Soup "/>
                    <dish name="Manhattan Clam Chowder "/>
                </food-category>
                <food-category name="The Entrees">
                    <dish name="Marinated Oven Roasted Tofu "/>
                    <dish name="Spinach Frittata With Ricotta "/>
                </food-category>
                <food-category name="The Express Bar">
                    <dish name="Cheese Sauce"/>
                    <dish name="Steakhouse French Fries "/>
                    <dish name="Brown Sauce"/>
                    <dish name="Black Pepper Mayonnaise "/>
                </food-category>
                <food-category name="The Grill">
                    <dish name="Hand Shaped Angus Hamurger "/>
                    <dish name="Hand Shaped Angus Cheeseburger "/>
                    <dish
                        name="Grilled-to-order Star Ranch All Natural Burgers &amp;amp; Cheeseburgers, All Natural Chicken Breasts, Jumbo All Beef Franks, Gardenburgers The Original, Gardenburger Black Bean Veggie Burgers, or Grilled Tofu, plus French Fries."/>
                </food-category>
                <food-category name="The Deli">
                    <dish name="Egg Salad Mixture "/>
                </food-category>
                <food-category name="The Vegetables">
                    <dish name="Baked Zucchini &amp;amp; Tomatoes "/>
                </food-category>
                <food-category name="The Salad">
                    <dish name="Mesclun, Fresh Mozzarella &amp;amp; Olives "/>
                    <dish name="Broccoli Olive &amp;amp; Ricotta Salata Salad "/>
                    <dish name="German Potato Salad "/>
                </food-category>
                <food-category name="The Sweets">
                    <dish name="Rootbeer Cupcake "/>
                    <dish name="Chocolate Chip Cookie "/>
                </food-category>
            </meal>
        </dining-hall>
    </menu-day>

    <menu-day date="2012-06-13">
        <dining-hall key="1" name="General">
            <meal name="Breakfast">
                <food-category name="First Course">
                    <dish name="Steelcut Oats "/>
                </food-category>
                <food-category name="The Entrees">
                    <dish name="Waffle Bar "/>
                </food-category>
                <food-category name="Morning Sweets">
                    <dish name="Cheddar &amp;amp; Green Onion Scone "/>
                </food-category>
            </meal>
            <meal name="Lunch">
                <food-category name="The Soup">
                    <dish name="Vegetarian French Onion Soup "/>
                    <dish name="Manhattan Clam Chowder "/>
                </food-category>
                <food-category name="The Entrees">
                    <dish name="Marinated Oven Roasted Tofu "/>
                    <dish name="Spinach Frittata With Ricotta "/>
                </food-category>
                <food-category name="The Express Bar">
                    <dish name="Cheese Sauce"/>
                    <dish name="Steakhouse French Fries "/>
                    <dish name="Brown Sauce"/>
                    <dish name="Black Pepper Mayonnaise "/>
                </food-category>
                <food-category name="The Grill">
                    <dish name="Hand Shaped Angus Hamurger "/>
                    <dish name="Hand Shaped Angus Cheeseburger "/>
                    <dish
                        name="Grilled-to-order Star Ranch All Natural Burgers &amp;amp; Cheeseburgers, All Natural Chicken Breasts, Jumbo All Beef Franks, Gardenburgers The Original, Gardenburger Black Bean Veggie Burgers, or Grilled Tofu, plus French Fries."/>
                </food-category>
                <food-category name="The Deli">
                    <dish name="Egg Salad Mixture "/>
                </food-category>
                <food-category name="The Vegetables">
                    <dish name="Baked Zucchini &amp;amp; Tomatoes "/>
                </food-category>
                <food-category name="The Salad">
                    <dish name="Mesclun, Fresh Mozzarella &amp;amp; Olives "/>
                    <dish name="Broccoli Olive &amp;amp; Ricotta Salata Salad "/>
                    <dish name="German Potato Salad "/>
                </food-category>
                <food-category name="The Sweets">
                    <dish name="Rootbeer Cupcake "/>
                    <dish name="Chocolate Chip Cookie "/>
                </food-category>
            </meal>
        </dining-hall>
    </menu-day>

</menu>
